version: '2'
services:

  ttyd:
    image: hackinglab/hl-kali-docker-ttyd
    labels:
      - "traefik.port=7681"
      - "traefik.frontend.rule=Host:ttyd.idocker.hacking-lab.com"
      - "traefik.protocol=http"
